/*
 * A QR CODE, FROM A STRING.
 *
 * The one piece of this feature that is a general-purpose algorithm rather than
 * something about raffles. It takes the verify address for a ticket and returns
 * a square of true/false modules; ticketart.js turns that into rectangles on the
 * artwork.
 *
 * WHY IT IS WRITTEN HERE RATHER THAN INSTALLED. This repository has three
 * runtime dependencies and a stated position that printing needs no library and
 * no server. A QR encoder is about four hundred lines with no dependencies of
 * its own and no reason to ever change, so a file is a smaller commitment than a
 * package — nothing to audit on upgrade, nothing to break on a `npm ci` in two
 * years, and it works in the browser and in node without a build step.
 *
 * WHY THAT IS SAFE TO SAY. Because it is checked against a real one.
 * tests/qr.test.mjs holds module-for-module fixtures generated by an
 * independent implementation, across versions, error-correction levels and
 * lengths. A QR encoder that is subtly wrong still produces a plausible-looking
 * square — it simply does not scan — so "it looks right" is worth nothing here
 * and the comparison is the whole basis for trusting this file.
 *
 * WHAT IT SUPPORTS: byte mode, versions 1 to 10, all four error-correction
 * levels. That is far more than a ticket needs — the verify address fits
 * version 4 at level M — and stops well short of the 40 versions the standard
 * allows, because nothing here will ever encode four kilobytes and the tables
 * for the rest are dead weight.
 *
 * The algorithm is the one in the specification, structured after Nayuki's
 * public-domain reference implementation, which is the clearest description of
 * it in any language.
 */

/** Error-correction levels, with the two-bit pattern each one is written as. */
export const ECC = {
  L: { ordinal: 0, formatBits: 1 },
  M: { ordinal: 1, formatBits: 0 },
  Q: { ordinal: 2, formatBits: 3 },
  H: { ordinal: 3, formatBits: 2 },
}

export const MIN_VERSION = 1
export const MAX_VERSION = 10

/* Error-correction codewords per block, by level then version (1-indexed). */
const ECC_CODEWORDS_PER_BLOCK = {
  L: [-1, 7, 10, 15, 20, 26, 18, 20, 24, 30, 18],
  M: [-1, 10, 16, 26, 18, 24, 16, 18, 22, 22, 26],
  Q: [-1, 13, 22, 18, 26, 18, 24, 18, 22, 20, 24],
  H: [-1, 17, 28, 22, 16, 22, 28, 26, 26, 24, 28],
}

/* How many blocks the data is split into, by level then version. */
const NUM_ECC_BLOCKS = {
  L: [-1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 4],
  M: [-1, 1, 1, 1, 2, 2, 4, 4, 4, 5, 5],
  Q: [-1, 1, 1, 2, 2, 4, 4, 6, 6, 8, 8],
  H: [-1, 1, 1, 2, 4, 4, 4, 5, 6, 8, 8],
}

/** Total data+ECC bits available in a version, before any of it is reserved. */
function rawDataModules(ver) {
  let result = (16 * ver + 128) * ver + 64
  if (ver >= 2) {
    const numAlign = Math.floor(ver / 7) + 2
    result -= (25 * numAlign - 10) * numAlign - 55
    if (ver >= 7) result -= 36
  }
  return result
}

/** How many data codewords a version holds at a level, after ECC is taken out. */
function dataCodewords(ver, ecl) {
  return Math.floor(rawDataModules(ver) / 8)
    - ECC_CODEWORDS_PER_BLOCK[ecl][ver] * NUM_ECC_BLOCKS[ecl][ver]
}

/* ---------- Reed-Solomon over GF(256) ---------- */

/** Multiply in the Galois field the standard uses: x^8 + x^4 + x^3 + x^2 + 1. */
function gfMul(x, y) {
  let z = 0
  for (let i = 7; i >= 0; i--) {
    z = ((z << 1) ^ ((z >>> 7) * 0x11d)) & 0xff
    z ^= ((y >>> i) & 1) * x
  }
  return z
}

/** The divisor polynomial for a given number of error-correction codewords. */
function rsDivisor(degree) {
  const result = new Uint8Array(degree)
  result[degree - 1] = 1
  let root = 1
  for (let i = 0; i < degree; i++) {
    for (let j = 0; j < degree; j++) {
      result[j] = gfMul(result[j], root)
      if (j + 1 < degree) result[j] ^= result[j + 1]
    }
    root = gfMul(root, 0x02)
  }
  return result
}

function rsRemainder(data, divisor) {
  const result = new Uint8Array(divisor.length)
  for (const b of data) {
    const factor = b ^ result[0]
    result.copyWithin(0, 1)
    result[result.length - 1] = 0
    for (let i = 0; i < divisor.length; i++) result[i] ^= gfMul(divisor[i], factor)
  }
  return result
}

/* ---------- bits ---------- */

class BitBuffer {
  constructor() { this.bits = [] }
  append(val, len) {
    for (let i = len - 1; i >= 0; i--) this.bits.push((val >>> i) & 1)
  }
}

/** UTF-8, because a verify address is ASCII but nothing should depend on that. */
function toBytes(text) {
  if (typeof TextEncoder !== 'undefined') return new TextEncoder().encode(text)
  return Uint8Array.from(unescape(encodeURIComponent(String(text))), (c) => c.charCodeAt(0))
}

/* ---------- the matrix ---------- */

function alignmentPositions(ver) {
  if (ver === 1) return []
  const numAlign = Math.floor(ver / 7) + 2
  const size = ver * 4 + 17
  const step = Math.ceil((ver * 4 + 4) / (numAlign * 2 - 2)) * 2
  const result = [6]
  for (let pos = size - 7; result.length < numAlign; pos -= step) result.splice(1, 0, pos)
  return result
}

class Matrix {
  constructor(size) {
    this.size = size
    this.modules = Array.from({ length: size }, () => new Array(size).fill(false))
    this.reserved = Array.from({ length: size }, () => new Array(size).fill(false))
  }

  set(x, y, dark, reserve = true) {
    if (x < 0 || y < 0 || x >= this.size || y >= this.size) return
    this.modules[y][x] = dark
    if (reserve) this.reserved[y][x] = true
  }

  /** A finder pattern and the light separator that has to surround it. */
  finder(cx, cy) {
    for (let dy = -4; dy <= 4; dy++) {
      for (let dx = -4; dx <= 4; dx++) {
        const dist = Math.max(Math.abs(dx), Math.abs(dy))
        this.set(cx + dx, cy + dy, dist !== 2 && dist !== 4)
      }
    }
  }

  alignment(cx, cy) {
    for (let dy = -2; dy <= 2; dy++) {
      for (let dx = -2; dx <= 2; dx++) {
        this.set(cx + dx, cy + dy, Math.max(Math.abs(dx), Math.abs(dy)) !== 1)
      }
    }
  }
}

function drawFunctionPatterns(m, ver) {
  const size = m.size

  // Timing patterns, before the finders so the finders overwrite their corners.
  for (let i = 0; i < size; i++) {
    m.set(6, i, i % 2 === 0)
    m.set(i, 6, i % 2 === 0)
  }

  m.finder(3, 3)
  m.finder(size - 4, 3)
  m.finder(3, size - 4)

  const pos = alignmentPositions(ver)
  for (let i = 0; i < pos.length; i++) {
    for (let j = 0; j < pos.length; j++) {
      // The three corners already hold finder patterns.
      if ((i === 0 && j === 0) || (i === 0 && j === pos.length - 1) || (i === pos.length - 1 && j === 0)) continue
      m.alignment(pos[i], pos[j])
    }
  }

  // Reserve the format areas; the real bits are written after masking.
  drawFormatBits(m, 'M', 0, true)

  if (ver >= 7) {
    let rem = ver
    for (let i = 0; i < 12; i++) rem = (rem << 1) ^ ((rem >>> 11) * 0x1f25)
    const bits = (ver << 12) | rem
    for (let i = 0; i < 18; i++) {
      const bit = ((bits >>> i) & 1) === 1
      const a = size - 11 + (i % 3)
      const b = Math.floor(i / 3)
      m.set(a, b, bit)
      m.set(b, a, bit)
    }
  }
}

function drawFormatBits(m, ecl, mask, reserveOnly = false) {
  const size = m.size
  const data = (ECC[ecl].formatBits << 3) | mask
  let rem = data
  for (let i = 0; i < 10; i++) rem = (rem << 1) ^ ((rem >>> 9) * 0x537)
  const bits = ((data << 10) | rem) ^ 0x5412
  const bit = (i) => (reserveOnly ? false : ((bits >>> i) & 1) === 1)

  for (let i = 0; i <= 5; i++) m.set(8, i, bit(i))
  m.set(8, 7, bit(6))
  m.set(8, 8, bit(7))
  m.set(7, 8, bit(8))
  for (let i = 9; i < 15; i++) m.set(14 - i, 8, bit(i))

  for (let i = 0; i < 8; i++) m.set(size - 1 - i, 8, bit(i))
  for (let i = 8; i < 15; i++) m.set(8, size - 15 + i, bit(i))
  // The one module that is always dark, in every code ever made.
  m.set(8, size - 8, true)
}

/** Data and ECC codewords, interleaved the way the standard requires. */
function addEccAndInterleave(data, ver, ecl) {
  const numBlocks = NUM_ECC_BLOCKS[ecl][ver]
  const blockEccLen = ECC_CODEWORDS_PER_BLOCK[ecl][ver]
  const rawCodewords = Math.floor(rawDataModules(ver) / 8)
  const numShortBlocks = numBlocks - (rawCodewords % numBlocks)
  const shortBlockLen = Math.floor(rawCodewords / numBlocks)

  const blocks = []
  const divisor = rsDivisor(blockEccLen)
  for (let i = 0, k = 0; i < numBlocks; i++) {
    const len = shortBlockLen - blockEccLen + (i < numShortBlocks ? 0 : 1)
    const dat = data.slice(k, k + len)
    k += len
    const ecc = rsRemainder(dat, divisor)
    blocks.push({ dat, ecc })
  }

  const result = []
  for (let i = 0; i < shortBlockLen - blockEccLen + 1; i++) {
    for (let j = 0; j < numBlocks; j++) {
      // The last byte of the long blocks comes after every short block's data.
      if (i < blocks[j].dat.length) result.push(blocks[j].dat[i])
    }
  }
  for (let i = 0; i < blockEccLen; i++) {
    for (let j = 0; j < numBlocks; j++) result.push(blocks[j].ecc[i])
  }
  return result
}

/** Zigzag up and down the two-module-wide columns, skipping the timing column. */
function drawCodewords(m, codewords) {
  const size = m.size
  let i = 0
  for (let right = size - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5
    for (let vert = 0; vert < size; vert++) {
      for (let j = 0; j < 2; j++) {
        const x = right - j
        const upward = ((right + 1) & 2) === 0
        const y = upward ? size - 1 - vert : vert
        if (!m.reserved[y][x] && i < codewords.length * 8) {
          m.modules[y][x] = ((codewords[i >>> 3] >>> (7 - (i & 7))) & 1) !== 0
          i++
        }
      }
    }
  }
}

const MASKS = [
  (x, y) => (x + y) % 2 === 0,
  (x, y) => y % 2 === 0,
  (x, y) => x % 3 === 0,
  (x, y) => (x + y) % 3 === 0,
  (x, y) => (Math.floor(x / 3) + Math.floor(y / 2)) % 2 === 0,
  (x, y) => ((x * y) % 2) + ((x * y) % 3) === 0,
  (x, y) => (((x * y) % 2) + ((x * y) % 3)) % 2 === 0,
  (x, y) => (((x + y) % 2) + ((x * y) % 3)) % 2 === 0,
]

function applyMask(m, mask) {
  for (let y = 0; y < m.size; y++) {
    for (let x = 0; x < m.size; x++) {
      if (!m.reserved[y][x] && MASKS[mask](x, y)) m.modules[y][x] = !m.modules[y][x]
    }
  }
}

/*
 * How ugly a masked code is, by the four rules in the standard.
 *
 * The point is not beauty: runs of the same colour, blocks, and anything that
 * looks like a finder pattern all make a scanner's job harder, and an unbalanced
 * code can fail on a cheap camera. The lowest-penalty mask is chosen.
 */
function penalty(m) {
  const size = m.size
  const mod = m.modules
  let result = 0

  // Rule 1: runs of five or more of the same colour, in both directions.
  for (let y = 0; y < size; y++) {
    let run = 1
    for (let x = 1; x < size; x++) {
      if (mod[y][x] === mod[y][x - 1]) { run++; if (run === 5) result += 3; else if (run > 5) result++ }
      else run = 1
    }
  }
  for (let x = 0; x < size; x++) {
    let run = 1
    for (let y = 1; y < size; y++) {
      if (mod[y][x] === mod[y - 1][x]) { run++; if (run === 5) result += 3; else if (run > 5) result++ }
      else run = 1
    }
  }

  // Rule 2: every 2x2 block of one colour.
  for (let y = 0; y < size - 1; y++) {
    for (let x = 0; x < size - 1; x++) {
      const c = mod[y][x]
      if (c === mod[y][x + 1] && c === mod[y + 1][x] && c === mod[y + 1][x + 1]) result += 3
    }
  }

  /*
   * Rule 3: anything a scanner could mistake for a finder pattern.
   *
   * The specification names two exact eleven-module sequences — the 1:1:3:1:1
   * dark pattern with four light modules on one side or the other — and this
   * looks for precisely those, in both directions, counting each occurrence.
   *
   * IT WAS WRITTEN THE CLEVER WAY FIRST and that was a real bug, not a style
   * preference. The first version looked for the seven-module core and then
   * counted four light modules either side, treating the edge of the symbol as
   * light. That fires far more often than the specification does — about
   * seventeen extra hits on a 25-module code — which inflated every mask's
   * score unevenly and made this function choose mask 2 for a repetitive
   * payload, the one mask of the eight whose output a real scanner could not
   * read. Seven of the other masks were fine. Matching the specification
   * literally is both simpler and correct.
   */
  const P1 = [true, false, true, true, true, false, true, false, false, false, false]
  const P2 = [false, false, false, false, true, false, true, true, true, false, true]
  const matches = (get, i, pat) => {
    for (let k = 0; k < 11; k++) if (get(i + k) !== pat[k]) return false
    return true
  }
  for (let y = 0; y < size; y++) {
    const get = (i) => mod[y][i]
    for (let x = 0; x + 10 < size; x++) {
      if (matches(get, x, P1)) result += 40
      if (matches(get, x, P2)) result += 40
    }
  }
  for (let x = 0; x < size; x++) {
    const get = (i) => mod[i][x]
    for (let y = 0; y + 10 < size; y++) {
      if (matches(get, y, P1)) result += 40
      if (matches(get, y, P2)) result += 40
    }
  }

  // Rule 4: how far from half the modules are dark.
  let dark = 0
  for (const row of mod) for (const c of row) if (c) dark++
  const total = size * size
  const k = Math.ceil(Math.abs(dark * 20 - total * 10) / total) - 1
  result += Math.max(0, k) * 10
  return result
}

/**
 * Encode `text` and return `{ size, modules, version, ecc }`.
 *
 * `modules` is an array of rows of booleans, true meaning dark. It carries NO
 * quiet zone — whatever draws it is responsible for the four modules of light
 * the standard requires around the outside, because on a ticket that light is
 * the artwork's own white backing rather than more of the code.
 */
export function encode(text, opts = {}) {
  const ecl = opts.ecc && ECC[opts.ecc] ? opts.ecc : 'M'
  const bytes = toBytes(text)

  // The smallest version that holds it, so the modules print as large as they can.
  let ver = -1
  for (let v = opts.minVersion ?? MIN_VERSION; v <= MAX_VERSION; v++) {
    // Mode indicator (4) + length (8 or 16 by version) + the data itself.
    const lenBits = v <= 9 ? 8 : 16
    const capacity = dataCodewords(v, ecl) * 8
    if (4 + lenBits + bytes.length * 8 <= capacity) { ver = v; break }
  }
  if (ver < 0) {
    throw new Error(
      `${bytes.length} bytes will not fit a QR code up to version ${MAX_VERSION} at level ${ecl}. ` +
      'Shorten the address the code points at.')
  }

  const bb = new BitBuffer()
  bb.append(0x4, 4)                                   // byte mode
  bb.append(bytes.length, ver <= 9 ? 8 : 16)
  for (const b of bytes) bb.append(b, 8)

  const capacity = dataCodewords(ver, ecl) * 8
  bb.append(0, Math.min(4, capacity - bb.bits.length))  // terminator
  bb.append(0, (8 - (bb.bits.length % 8)) % 8)          // to a whole byte
  // The two pad bytes the standard names, alternating, until it is full.
  for (let pad = 0xec; bb.bits.length < capacity; pad ^= 0xec ^ 0x11) bb.append(pad, 8)

  const dataCw = new Uint8Array(bb.bits.length / 8)
  bb.bits.forEach((bit, i) => { dataCw[i >>> 3] |= bit << (7 - (i & 7)) })

  const all = addEccAndInterleave(dataCw, ver, ecl)

  const size = ver * 4 + 17
  const m = new Matrix(size)
  drawFunctionPatterns(m, ver)
  drawCodewords(m, all)

  // Try every mask, keep the one a scanner will find easiest.
  let best = -1
  let bestPenalty = Infinity
  let bestModules = null
  for (let mask = 0; mask < 8; mask++) {
    applyMask(m, mask)
    drawFormatBits(m, ecl, mask)
    const p = penalty(m)
    if (p < bestPenalty) {
      bestPenalty = p
      best = mask
      bestModules = m.modules.map((r) => r.slice())
    }
    applyMask(m, mask)   // the masks are their own inverse
  }

  return { size, modules: bestModules, version: ver, ecc: ecl, mask: best }
}
